package main

import (
	"context"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"

	gitstore "github.com/hyper-swe/mgit/internal/store/git"
)

// addCmd implements mgit add. Refs: FR-8.15, MGIT-4.2.6
func addCmd() *cobra.Command {
	var all bool
	var taskScope string

	cmd := &cobra.Command{
		Use:   "add [paths...]",
		Short: "Stage files for the next commit",
		RunE: func(cmd *cobra.Command, args []string) error {
			// --task is advisory; stored as metadata for future use.
			_ = taskScope
			app, err := openAppFromCwd()
			if err != nil {
				return err
			}
			defer app.Close()

			ctx := context.Background()
			ws := gitstore.NewWorktreeStore(app.Repo)

			if all {
				// Stage all changes
				if err := ws.Add(ctx, "."); err != nil {
					return fmt.Errorf("add all: %w", err)
				}
				_, _ = fmt.Fprintln(os.Stdout, "Staged all changes")
				return nil
			}

			if len(args) == 0 {
				return fmt.Errorf("specify files to add, or use --all")
			}

			for _, path := range args {
				if err := ws.Add(ctx, path); err != nil {
					return fmt.Errorf("add %s: %w", path, err)
				}
				_, _ = fmt.Fprintf(os.Stdout, "Staged: %s\n", path)
				warnIfGenerated(cmd.ErrOrStderr(), ws, path)
			}
			return nil
		},
	}

	cmd.Flags().BoolVarP(&all, "all", "A", false, "Stage all changes")
	bindTaskIDFlag(cmd, &taskScope, "Task ID scope (advisory — stored as metadata for future use)")
	return cmd
}

// warnIfGenerated notes on stderr that an EXPLICITLY named path is one mgit
// generated into this worktree. Naming a path is honored — it is an
// unambiguous statement of intent, and a user editing their own CLAUDE.md must
// be able to commit it (ADR-013) — but it is not silent: the file also carries
// mgit's generated block, which is worktree- and host-specific and will land
// with it. Bulk staging (`-A`, `.`, `mgit commit -a`) skips these paths, so this
// warning only ever fires on a deliberate choice. A classification failure is
// not worth failing a successful stage over. Refs: MGIT-80
func warnIfGenerated(warn io.Writer, ws *gitstore.WorktreeStore, path string) {
	generated, err := ws.IsGenerated(path)
	if err != nil || !generated {
		return
	}
	_, _ = fmt.Fprintf(warn, "note: %s was generated by mgit for this worktree; "+
		"staging it by name also commits mgit's generated block, which is specific to "+
		"this worktree and host. `mgit commit -a` alone would have skipped it.\n", path)
}
