package main

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"

	"github.com/hyper-swe/mgit/internal/model"
	gitstore "github.com/hyper-swe/mgit/internal/store/git"
)

// addCmd implements mgit add. Refs: FR-8.15, MGIT-4.2.6
func addCmd() *cobra.Command {
	var all, allowLarge bool
	var taskScope string

	cmd := &cobra.Command{
		Use:   "add [paths...]",
		Short: "Stage files for the next commit",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Past flag parsing a failure is a runtime condition, not misuse:
			// the size refusal carries a remedy the flag table would bury.
			// Refs: MGIT-131, MGIT-77
			cmd.SilenceUsage = true

			// --task is advisory; stored as metadata for future use.
			_ = taskScope
			app, err := openAppFromCwd()
			if err != nil {
				return err
			}
			defer app.Close()

			ctx := context.Background()
			// The size tripwire applies to BOTH staging paths — here and in
			// `mgit commit -a` (service.CommitService) — because a guard on one
			// of them is not a guard. Refs: MGIT-131
			ws := gitstore.NewWorktreeStore(app.Repo).
				WithMaxStagedFileBytes(stagingLimit(app, allowLarge))

			if all {
				// Stage all changes
				if err := ws.Add(ctx, "."); err != nil {
					return addError("add all", err)
				}
				_, _ = fmt.Fprintln(os.Stdout, "Staged all changes")
				return nil
			}

			if len(args) == 0 {
				return fmt.Errorf("specify files to add, or use --all")
			}

			for _, path := range args {
				if err := ws.Add(ctx, path); err != nil {
					return addError("add "+path, err)
				}
				_, _ = fmt.Fprintf(os.Stdout, "Staged: %s\n", path)
				warnIfGenerated(cmd.ErrOrStderr(), ws, path)
			}
			return nil
		},
	}

	cmd.Flags().BoolVarP(&all, "all", "A", false, "Stage all changes")
	cmd.Flags().BoolVar(&allowLarge, "allow-large", false,
		"Stage files over the limits.max_staged_file_mb size limit")
	bindTaskIDFlag(cmd, &taskScope, "Task ID scope (advisory — stored as metadata for future use)")
	return cmd
}

// addError adds the caller's context to a staging failure — except for the
// size refusal, which is returned bare. That message already names the file,
// its size, the limit and both overrides; an "add <path>:" prefix only repeats
// the path and pushes the remedy further from the reader's eye.
// Refs: FR-8.15, MGIT-131
func addError(context string, err error) error {
	if errors.Is(err, model.ErrFileTooLarge) {
		return err
	}
	return fmt.Errorf("%s: %w", context, err)
}

// stagingLimit resolves the per-file staging size limit for one invocation:
// `limits.max_staged_file_mb` from the repo config, or 0 (guard off) when the
// caller passed --allow-large. Refs: FR-13, MGIT-131
func stagingLimit(app *App, allowLarge bool) int64 {
	if allowLarge {
		return 0
	}
	return app.StagedFileLimit
}

// warnIfGenerated notes on stderr that an EXPLICITLY named path is one mgit
// generated into this worktree. Naming a path is honored — it is an
// unambiguous statement of intent, and a user editing their own CLAUDE.md must
// be able to commit it (ADR-013) — but it is not silent: the file also carries
// mgit's generated block, which is worktree- and host-specific and will land
// with it. Bulk staging (`-A`, `.`, `mgit commit -a`) skips these paths, so this
// warning only ever fires on a deliberate choice. A classification failure is
// not worth failing a successful stage over. Refs: MGIT-80
func warnIfGenerated(warn io.Writer, ws *gitstore.WorktreeStore, path string) {
	generated, err := ws.IsGenerated(path)
	if err != nil || !generated {
		return
	}
	_, _ = fmt.Fprintf(warn, "note: %s was generated by mgit for this worktree; "+
		"staging it by name also commits mgit's generated block, which is specific to "+
		"this worktree and host. `mgit commit -a` alone would have skipped it.\n", path)
}
